# -*- coding: utf-8 -*-
"""Gradio_Image_Augmentor.ipynb

Automatically generated by Colab.

Gemini Image Editor - Google Colab Version
Optimized for Google Colab with proper display and file handling
Now with Depth Map generation!
"""

import os
import gradio as gr
from google import genai
from google.genai import types
from PIL import Image
import io
from transformers import pipeline

# Initialize Gemini client
# Replace with your API key
api_key = os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=api_key)

# Initialize Depth Anything pipeline (loaded once at startup)
print("Loading Depth Anything model...")
depth_pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Small-hf")
print("Depth model loaded successfully!")

def edit_image(image, prompt_text):
    """
    Edit an image using Gemini's image generation model based on custom prompt

    Args:
        image: PIL Image uploaded by user
        prompt_text: Custom editing instructions from user

    Returns:
        Edited image or error message
    """
    try:
        if image is None:
            return None, "Please upload an image first."

        if not prompt_text or prompt_text.strip() == "":
            return None, "Please enter editing instructions."

        # Convert PIL Image to bytes for Gemini
        img_byte_arr = io.BytesIO()
        image.save(img_byte_arr, format='PNG')
        img_byte_arr = img_byte_arr.getvalue()

        # Create properly formatted content for Gemini
        contents = [
            types.Content(
                role="user",
                parts=[
                    types.Part.from_text(text=prompt_text),
                    types.Part.from_bytes(
                        data=img_byte_arr,
                        mime_type="image/png"
                    ),
                ],
            ),
        ]

        # Configure for image generation
        generate_content_config = types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                image_size="1K",
            ),
        )

        # Generate edited image using Gemini with streaming
        edited_image = None
        response_text = ""
        chunk_count = 0

        for chunk in client.models.generate_content_stream(
            model="gemini-2.5-flash-image",
            contents=contents,
            config=generate_content_config,
        ):
            chunk_count += 1

            if (
                chunk.candidates is None
                or chunk.candidates[0].content is None
                or chunk.candidates[0].content.parts is None
            ):
                continue

            # Check for image data
            for part in chunk.candidates[0].content.parts:
                if part.inline_data and part.inline_data.data:
                    inline_data = part.inline_data
                    data_buffer = inline_data.data

                    # Convert bytes to PIL Image
                    edited_image = Image.open(io.BytesIO(data_buffer))
                    # Ensure image is in RGB mode for proper display
                    if edited_image.mode != 'RGB':
                        edited_image = edited_image.convert('RGB')
                    break

            # Collect text response
            if hasattr(chunk, 'text') and chunk.text:
                response_text += chunk.text

        if edited_image:
            # Verify image dimensions
            width, height = edited_image.size
            return edited_image, f"✅ Image edited successfully! Size: {width}x{height}"
        elif response_text:
            return None, f"⚠️ No image generated. Response: {response_text}"
        else:
            return None, "❌ No image was generated. Please try a different prompt."

    except Exception as e:
        return None, f"❌ Error: {str(e)}"

def generate_depth_map(image):
    """
    Generate a depth map heat map from an image using Depth Anything V2

    Args:
        image: PIL Image (either original or edited)

    Returns:
        Depth map as PIL Image and status message
    """
    try:
        if image is None:
            return None, "❌ No image available. Please upload or generate an image first."

        # Generate depth map
        depth_result = depth_pipe(image)
        depth_map = depth_result["depth"]

        # Convert to RGB if needed for display
        if depth_map.mode != 'RGB':
            depth_map = depth_map.convert('RGB')

        width, height = depth_map.size
        return depth_map, f"✅ Depth map generated successfully! Size: {width}x{height}"

    except Exception as e:
        return None, f"❌ Error generating depth map: {str(e)}"

# Example prompts for user guidance
example_prompt = """make the jacket red"""

prompt_template = """Using the provided image of [subject], please [add/remove/modify] [element] to/from the scene. Ensure the change is [description of how the change should integrate]."""

# Create Gradio interface optimized for Colab
with gr.Blocks(title="Gemini Image Editor + Depth Map", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🎨 Gemini Image Editor + 🗺️ Depth Map Generator")
    gr.Markdown("Upload an image, edit it with AI, and generate depth maps!")

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(
                type="pil",
                label="📤 Upload Image",
                height=350
            )

            prompt_input = gr.Textbox(
                label="✏️ Editing Instructions",
                placeholder="Describe what changes you want to make...",
                lines=4,
                value=example_prompt
            )

            edit_button = gr.Button("✨ Edit Image", variant="primary", size="lg")

            gr.Markdown("### 💡 Prompt Template:")
            gr.Markdown(f"`{prompt_template}`")

        with gr.Column(scale=1):
            image_output = gr.Image(
                label="📥 Edited Image",
                height=350,
                type="pil",
                interactive=False,
                show_download_button=True
            )
            status_output = gr.Textbox(
                label="📊 Status",
                lines=2,
                interactive=False
            )

            # Add Depth Map button and output
            depth_button = gr.Button("🗺️ Generate Depth Map", variant="secondary", size="lg")

    with gr.Row():
        with gr.Column(scale=1):
            depth_output = gr.Image(
                label="🌡️ Depth Heat Map",
                height=350,
                type="pil",
                interactive=False,
                show_download_button=True
            )
            depth_status = gr.Textbox(
                label="📊 Depth Map Status",
                lines=2,
                interactive=False
            )

    # Examples section
    gr.Markdown("### 📝 Quick Example Prompts:")

    with gr.Row():
        gr.Examples(
            examples=[
                ["make the jacket red"],
                ["add sunglasses"],
                ["change to black and white"],
                ["make it look like sunset"],
            ],
            inputs=prompt_input,
            label="Click to use:"
        )

    gr.Markdown("### 🎯 More Example Prompts:")
    gr.Markdown("""
    - `make the jacket red`
    - `change the wall color to blue`
    - `add a wizard hat on the cat's head`
    - `remove the background and replace with a beach scene`
    - `add sunglasses to the person`
    - `convert to black and white vintage style`
    - `add a plant in the corner`
    - `make the lighting look like sunset`
    """)

    # Connect the edit button to the function
    edit_button.click(
        fn=edit_image,
        inputs=[image_input, prompt_input],
        outputs=[image_output, status_output]
    )

    # Connect the depth map button - generates from edited image
    depth_button.click(
        fn=generate_depth_map,
        inputs=[image_output],
        outputs=[depth_output, depth_status]
    )

    gr.Markdown("---")
    gr.Markdown("💡 **Tips:**")
    gr.Markdown("- Right-click on any image to save it, or use the download buttons!")
    gr.Markdown("- Generate a depth map from either the original uploaded image or the edited image")
    gr.Markdown("- Depth maps show distance: warmer colors (red/yellow) = closer, cooler colors (blue/purple) = farther")

# Launch for Colab - this will create a public link automatically
if __name__ == "__main__":
    # Colab-specific launch settings
    demo.launch(
        share=True,  # Creates public gradio.live link
        debug=False,
        show_error=True
    )